[package]
name = "wasmer"
version = "1.0.2"

[lib]
name = "wasmer"
crate-type = ["staticlib"]
path = "wasmer.rs"

[dependencies.wasmer-c-api]
version = "1.0.2"
default-features = false
features = ["jit", "cranelift", "wasi"]
