[package]
name = "wasmer"
version = "2.0.0"

[lib]
name = "wasmer"
crate-type = ["staticlib"]
path = "wasmer.rs"

[dependencies.wasmer-c-api]
version = "2.0.0"
default-features = false
features = ["jit", "cranelift", "wasi", "universal"]
