name: wasm
version: 0.1.0+1
description: Utilities for loading and running WASM modules from Dart code
repository: https://github.com/dart-lang/wasm

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^1.0.0
  package_config: ^2.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
