name: wasm
version: 0.1.0
description: Utilities for loading and running WASM modules from Dart code
homepage: https://github.com/dart-lang/sdk/tree/master/pkg/wasm

environment:
  sdk: '>=2.13.1 <3.0.0'

dependencies:
  ffi: ^1.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
