name: flutter_wasm_example
description: Demonstrates how to use the flutter_wasm plugin.
publish_to: 'none'

environment:
  sdk: ">=2.15.0-96.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_wasm:
    path: ../
  wasm:
    git:
      url: git@github.com:dart-lang/wasm.git
      path: wasm
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

