name: wasm
version: 0.2.0-dev
description: Utilities for loading and running WASM modules from Dart code
repository: https://github.com/dart-lang/wasm/tree/main/wasm

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  args: ^2.3.0
  ffi: ^2.0.0
  package_config: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
