[package]
name = "wasmer"
version = "2.1.0"

[lib]
name = "wasmer"
crate-type = ["staticlib"]
path = "wasmer.rs"

[profile.release]
opt-level = 'z'
debug = false
debug-assertions = false
overflow-checks = false
lto = true
panic = 'abort'
incremental = false
codegen-units = 1
rpath = false

[dependencies.wasmer-c-api]
version = "2.1.0"
default-features = false
#features = ["jit", "cranelift", "wasi", "universal"]
#features = ["cranelift", "native", "wasi"]
features = ["native", "wasi"]
